// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/distributedhashtable/messageexchange/MessageExchange.proto

package com.distributedhashtable.messageexchange;

public final class TransferMessages {
  private TransferMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessagesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string typeOfMessage = 1;
    boolean hasTypeOfMessage();
    String getTypeOfMessage();
    
    // required string transferMessage = 2;
    boolean hasTransferMessage();
    String getTransferMessage();
    
    // optional string key = 3;
    boolean hasKey();
    String getKey();
    
    // optional string value = 4;
    boolean hasValue();
    String getValue();
    
    // optional string keyHash = 5;
    boolean hasKeyHash();
    String getKeyHash();
    
    // optional string ipaddress = 6;
    boolean hasIpaddress();
    String getIpaddress();
    
    // optional int32 socket = 7;
    boolean hasSocket();
    int getSocket();
    
    // optional int32 sendOrRecieve = 8;
    boolean hasSendOrRecieve();
    int getSendOrRecieve();
  }
  public static final class Messages extends
      com.google.protobuf.GeneratedMessage
      implements MessagesOrBuilder {
    // Use Messages.newBuilder() to construct.
    private Messages(Builder builder) {
      super(builder);
    }
    private Messages(boolean noInit) {}
    
    private static final Messages defaultInstance;
    public static Messages getDefaultInstance() {
      return defaultInstance;
    }
    
    public Messages getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.distributedhashtable.messageexchange.TransferMessages.internal_static_messageexchange_Messages_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.distributedhashtable.messageexchange.TransferMessages.internal_static_messageexchange_Messages_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string typeOfMessage = 1;
    public static final int TYPEOFMESSAGE_FIELD_NUMBER = 1;
    private java.lang.Object typeOfMessage_;
    public boolean hasTypeOfMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTypeOfMessage() {
      java.lang.Object ref = typeOfMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          typeOfMessage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeOfMessageBytes() {
      java.lang.Object ref = typeOfMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        typeOfMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string transferMessage = 2;
    public static final int TRANSFERMESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object transferMessage_;
    public boolean hasTransferMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTransferMessage() {
      java.lang.Object ref = transferMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          transferMessage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTransferMessageBytes() {
      java.lang.Object ref = transferMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        transferMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string key = 3;
    public static final int KEY_FIELD_NUMBER = 3;
    private java.lang.Object key_;
    public boolean hasKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          key_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string value = 4;
    public static final int VALUE_FIELD_NUMBER = 4;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string keyHash = 5;
    public static final int KEYHASH_FIELD_NUMBER = 5;
    private java.lang.Object keyHash_;
    public boolean hasKeyHash() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getKeyHash() {
      java.lang.Object ref = keyHash_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          keyHash_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getKeyHashBytes() {
      java.lang.Object ref = keyHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        keyHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string ipaddress = 6;
    public static final int IPADDRESS_FIELD_NUMBER = 6;
    private java.lang.Object ipaddress_;
    public boolean hasIpaddress() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getIpaddress() {
      java.lang.Object ref = ipaddress_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ipaddress_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIpaddressBytes() {
      java.lang.Object ref = ipaddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ipaddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 socket = 7;
    public static final int SOCKET_FIELD_NUMBER = 7;
    private int socket_;
    public boolean hasSocket() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getSocket() {
      return socket_;
    }
    
    // optional int32 sendOrRecieve = 8;
    public static final int SENDORRECIEVE_FIELD_NUMBER = 8;
    private int sendOrRecieve_;
    public boolean hasSendOrRecieve() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getSendOrRecieve() {
      return sendOrRecieve_;
    }
    
    private void initFields() {
      typeOfMessage_ = "";
      transferMessage_ = "";
      key_ = "";
      value_ = "";
      keyHash_ = "";
      ipaddress_ = "";
      socket_ = 0;
      sendOrRecieve_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTypeOfMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTransferMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeOfMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTransferMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getValueBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getKeyHashBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getIpaddressBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, socket_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, sendOrRecieve_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeOfMessageBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTransferMessageBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getKeyBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getValueBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getKeyHashBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getIpaddressBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, socket_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, sendOrRecieve_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.distributedhashtable.messageexchange.TransferMessages.Messages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.distributedhashtable.messageexchange.TransferMessages.Messages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.distributedhashtable.messageexchange.TransferMessages.Messages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.distributedhashtable.messageexchange.TransferMessages.Messages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.distributedhashtable.messageexchange.TransferMessages.Messages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.distributedhashtable.messageexchange.TransferMessages.Messages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.distributedhashtable.messageexchange.TransferMessages.Messages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.distributedhashtable.messageexchange.TransferMessages.Messages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.distributedhashtable.messageexchange.TransferMessages.Messages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.distributedhashtable.messageexchange.TransferMessages.Messages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.distributedhashtable.messageexchange.TransferMessages.Messages prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.distributedhashtable.messageexchange.TransferMessages.MessagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.distributedhashtable.messageexchange.TransferMessages.internal_static_messageexchange_Messages_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.distributedhashtable.messageexchange.TransferMessages.internal_static_messageexchange_Messages_fieldAccessorTable;
      }
      
      // Construct using com.distributedhashtable.messageexchange.TransferMessages.Messages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        typeOfMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        transferMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        keyHash_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        ipaddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        socket_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        sendOrRecieve_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.distributedhashtable.messageexchange.TransferMessages.Messages.getDescriptor();
      }
      
      public com.distributedhashtable.messageexchange.TransferMessages.Messages getDefaultInstanceForType() {
        return com.distributedhashtable.messageexchange.TransferMessages.Messages.getDefaultInstance();
      }
      
      public com.distributedhashtable.messageexchange.TransferMessages.Messages build() {
        com.distributedhashtable.messageexchange.TransferMessages.Messages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.distributedhashtable.messageexchange.TransferMessages.Messages buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.distributedhashtable.messageexchange.TransferMessages.Messages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.distributedhashtable.messageexchange.TransferMessages.Messages buildPartial() {
        com.distributedhashtable.messageexchange.TransferMessages.Messages result = new com.distributedhashtable.messageexchange.TransferMessages.Messages(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.typeOfMessage_ = typeOfMessage_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.transferMessage_ = transferMessage_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.keyHash_ = keyHash_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ipaddress_ = ipaddress_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.socket_ = socket_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.sendOrRecieve_ = sendOrRecieve_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.distributedhashtable.messageexchange.TransferMessages.Messages) {
          return mergeFrom((com.distributedhashtable.messageexchange.TransferMessages.Messages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.distributedhashtable.messageexchange.TransferMessages.Messages other) {
        if (other == com.distributedhashtable.messageexchange.TransferMessages.Messages.getDefaultInstance()) return this;
        if (other.hasTypeOfMessage()) {
          setTypeOfMessage(other.getTypeOfMessage());
        }
        if (other.hasTransferMessage()) {
          setTransferMessage(other.getTransferMessage());
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasKeyHash()) {
          setKeyHash(other.getKeyHash());
        }
        if (other.hasIpaddress()) {
          setIpaddress(other.getIpaddress());
        }
        if (other.hasSocket()) {
          setSocket(other.getSocket());
        }
        if (other.hasSendOrRecieve()) {
          setSendOrRecieve(other.getSendOrRecieve());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTypeOfMessage()) {
          
          return false;
        }
        if (!hasTransferMessage()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              typeOfMessage_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              transferMessage_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              key_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              value_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              keyHash_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              ipaddress_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              socket_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              sendOrRecieve_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string typeOfMessage = 1;
      private java.lang.Object typeOfMessage_ = "";
      public boolean hasTypeOfMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTypeOfMessage() {
        java.lang.Object ref = typeOfMessage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          typeOfMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTypeOfMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        typeOfMessage_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypeOfMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        typeOfMessage_ = getDefaultInstance().getTypeOfMessage();
        onChanged();
        return this;
      }
      void setTypeOfMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        typeOfMessage_ = value;
        onChanged();
      }
      
      // required string transferMessage = 2;
      private java.lang.Object transferMessage_ = "";
      public boolean hasTransferMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTransferMessage() {
        java.lang.Object ref = transferMessage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          transferMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTransferMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        transferMessage_ = value;
        onChanged();
        return this;
      }
      public Builder clearTransferMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        transferMessage_ = getDefaultInstance().getTransferMessage();
        onChanged();
        return this;
      }
      void setTransferMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        transferMessage_ = value;
        onChanged();
      }
      
      // optional string key = 3;
      private java.lang.Object key_ = "";
      public boolean hasKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      void setKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
      }
      
      // optional string value = 4;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        value_ = value;
        onChanged();
      }
      
      // optional string keyHash = 5;
      private java.lang.Object keyHash_ = "";
      public boolean hasKeyHash() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getKeyHash() {
        java.lang.Object ref = keyHash_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          keyHash_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setKeyHash(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        keyHash_ = value;
        onChanged();
        return this;
      }
      public Builder clearKeyHash() {
        bitField0_ = (bitField0_ & ~0x00000010);
        keyHash_ = getDefaultInstance().getKeyHash();
        onChanged();
        return this;
      }
      void setKeyHash(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        keyHash_ = value;
        onChanged();
      }
      
      // optional string ipaddress = 6;
      private java.lang.Object ipaddress_ = "";
      public boolean hasIpaddress() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getIpaddress() {
        java.lang.Object ref = ipaddress_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ipaddress_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIpaddress(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ipaddress_ = value;
        onChanged();
        return this;
      }
      public Builder clearIpaddress() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ipaddress_ = getDefaultInstance().getIpaddress();
        onChanged();
        return this;
      }
      void setIpaddress(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        ipaddress_ = value;
        onChanged();
      }
      
      // optional int32 socket = 7;
      private int socket_ ;
      public boolean hasSocket() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getSocket() {
        return socket_;
      }
      public Builder setSocket(int value) {
        bitField0_ |= 0x00000040;
        socket_ = value;
        onChanged();
        return this;
      }
      public Builder clearSocket() {
        bitField0_ = (bitField0_ & ~0x00000040);
        socket_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 sendOrRecieve = 8;
      private int sendOrRecieve_ ;
      public boolean hasSendOrRecieve() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getSendOrRecieve() {
        return sendOrRecieve_;
      }
      public Builder setSendOrRecieve(int value) {
        bitField0_ |= 0x00000080;
        sendOrRecieve_ = value;
        onChanged();
        return this;
      }
      public Builder clearSendOrRecieve() {
        bitField0_ = (bitField0_ & ~0x00000080);
        sendOrRecieve_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:messageexchange.Messages)
    }
    
    static {
      defaultInstance = new Messages(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:messageexchange.Messages)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messageexchange_Messages_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messageexchange_Messages_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n>com/distributedhashtable/messageexchan" +
      "ge/MessageExchange.proto\022\017messageexchang" +
      "e\"\241\001\n\010Messages\022\025\n\rtypeOfMessage\030\001 \002(\t\022\027\n" +
      "\017transferMessage\030\002 \002(\t\022\013\n\003key\030\003 \001(\t\022\r\n\005v" +
      "alue\030\004 \001(\t\022\017\n\007keyHash\030\005 \001(\t\022\021\n\tipaddress" +
      "\030\006 \001(\t\022\016\n\006socket\030\007 \001(\005\022\025\n\rsendOrRecieve\030" +
      "\010 \001(\005B<\n(com.distributedhashtable.messag" +
      "eexchangeB\020TransferMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messageexchange_Messages_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messageexchange_Messages_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messageexchange_Messages_descriptor,
              new java.lang.String[] { "TypeOfMessage", "TransferMessage", "Key", "Value", "KeyHash", "Ipaddress", "Socket", "SendOrRecieve", },
              com.distributedhashtable.messageexchange.TransferMessages.Messages.class,
              com.distributedhashtable.messageexchange.TransferMessages.Messages.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
